spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
